name: netbootxyz
description: Your favorite operating systems in one place!
annotations:
  title: Netboot.xyz
type: application
version: 1.0.0
apiVersion: v2
appVersion: 0.6.7-nbxyz25
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.0.8
home: https://github.com/netbootxyz/netboot.xyz
icon: https://avatars.githubusercontent.com/u/16745498
sources:
  - https://github.com/netbootxyz/docker-netbootxyz
  - https://github.com/truenas/charts/tree/master/community/netbootxyz
  - https://hub.docker.com/r/netbootxyz/netbootxyz
keywords:
  - tftp
  - netboot
